In [6]:
!pip install plotly

Collecting plotly
  Downloading https://files.pythonhosted.org/packages/70/19/8437e22c84083a6d5d8a3c80f4edc73c9dcbb89261d07e6bd13b48752bbd/plotly-4.1.1-py2.py3-none-any.whl (7.1MB)
     |████████████████████████████████| 7.1MB 3.7MB/s
Requirement already satisfied: six in /home/broken-haiku/anaconda3/lib/python3.6/site-packages (from plotly) (1.11.0)
Collecting retrying>=1.3.3 (from plotly)
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-cp36-none-any.whl size=6236 sha256=87a0c0f1d67584de6a378e8ddeba5a41d69d1c3dc2c98669d8770f8e4d522f96
  Stored in directory: /home/broken-haiku/.cache/pip/wheels/d7/a9/33/acc7b709e2a35caa7d4cae442f6fe6fbf2c43f80823d46460c
Successfully built retrying
Installing collected packages: retrying, plotly
Successfully installed plotly-4.1.1 retrying-1.3.3

In [9]:
!pip install iso3166

Collecting iso3166
  Downloading https://files.pythonhosted.org/packages/18/ef/9b3c2df2b15746f04d2af4560e31b884f84092c8cd39c1c7bee81973d7d8/iso3166-1.0-py2.py3-none-any.whl
Installing collected packages: iso3166
Successfully installed iso3166-1.0

In [45]:
import pandas as pd
import iso3166
import gdelt
import plotly.express as px
import numpy as np

In [3]:
gd2 = gdelt.gdelt(version=2)
results = gd2.Search(['2016 11 01'],table='events',coverage=True)

/home/broken-haiku/anaconda3/lib/python3.6/site-packages/gdelt/parallel.py:67: UserWarning: GDELT does not have a url for date time 20161101233000
  warnings.warn(message)
/home/broken-haiku/anaconda3/lib/python3.6/site-packages/gdelt/parallel.py:103: UserWarning: GDELT did not return data for date time 20161101233000
  warnings.warn(message)

In [46]:
my_bool = results["ActionGeo_CountryCode"].isin([countries[key].alpha2 for key in countries.keys()])
my_bool = np.array(my_bool)

In [49]:
not_my_bool = map(lambda x: not x,my_bool)

In [56]:
results[results["ActionGeo_CountryCode"].isin([countries[key].alpha2 for key in countries.keys()])]

,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,594563052,20151102,201511,2015,2015.8274,NaN,NaN,NaN,NaN,NaN,...,3,"Boston, Massachusetts, United States",US,USMA,MA025,42.35840,-71.05980,617565,20161101011500,http://www.eagletribune.com/news/new_hampshire...
1,594563053,20151102,201511,2015,2015.8274,NaN,NaN,NaN,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101011500,http://chicagoinno.streetwise.co/2016/10/31/st...
2,594563054,20151102,201511,2015,2015.8274,CVLJUD,COMMUNITY,NaN,NaN,NaN,...,5,"Auckland, Auckland, New Zealand",NZ,NZE7,22379,-36.75000,174.58300,11483124,20161101011500,http://www.scoop.co.nz/stories/PO1611/S00007/c...
4,594563056,20151102,201511,2015,2015.8274,KOR,SOUTH KOREA,KOR,NaN,NaN,...,1,China,CH,CH,NaN,35.00000,105.00000,CH,20161101011500,http://english.yonhapnews.co.kr/business/2016/...
6,594563058,20151102,201511,2015,2015.8274,LBY,LIBYA,LBY,NaN,NaN,...,1,Libya,LY,LY,NaN,25.00000,17.00000,LY,20161101011500,http://www.thecommonsenseshow.com/2016/10/31/w...
7,594563059,20151102,201511,2015,2015.8274,TUR,TURKISH,TUR,NaN,NaN,...,3,"Boston, Massachusetts, United States",US,USMA,MA025,42.35840,-71.05980,617565,20161101011500,http://www.eagletribune.com/news/new_hampshire...
8,594563060,20151102,201511,2015,2015.8274,TWN,TAIPEI,TWN,NaN,NaN,...,1,Singapore,SN,SN,NaN,1.36670,103.80000,SN,20161101011500,http://www.straitstimes.com/singapore/much-rid...
9,594563061,20151102,201511,2015,2015.8274,USA,ILLINOIS,USA,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101011500,http://chicagoinno.streetwise.co/2016/10/31/st...
10,594563062,20151102,201511,2015,2015.8274,USA,CALIFORNIA,USA,NaN,NaN,...,3,"Dodger Stadium, California, United States",US,USCA,NaN,34.07360,-118.24100,1654613,20161101011500,http://www.bostonglobe.com/news/nation/2016/10...
11,594563063,20161002,201610,2016,2016.7452,NaN,NaN,NaN,NaN,NaN,...,4,"Algiers, Alger, Algeria",AG,AG01,37774,36.76310,3.05056,-458371,20161101011500,http://www.businesstimes.com.sg:80/energy-comm...
12,594563064,20161002,201610,2016,2016.7452,AUT,VIENNA,AUT,NaN,NaN,...,4,"Algiers, Alger, Algeria",AG,AG01,37774,36.76310,3.05056,-458371,20161101011500,http://www.businesstimes.com.sg:80/energy-comm...
14,594563066,20161002,201610,2016,2016.7452,LAB,WORKER,NaN,NaN,NaN,...,3,"Atlanta, Georgia, United States",US,USGA,GA121,33.74900,-84.38800,351615,20161101011500,http://www.wsoctv.com/news/national/authoritie...
15,594563067,20161002,201610,2016,2016.7452,MIL,ARMY,NaN,NaN,NaN,...,5,"Balochistan, Balochistan, Pakistan",PK,PK02,40300,28.47850,65.64360,-2755738,20161101011500,https://www.thenews.com.pk/print/161437-Quetta...
16,594563068,20161002,201610,2016,2016.7452,MIL,ARMY,NaN,NaN,NaN,...,4,"Quetta, Balochistan, Pakistan",PK,PK02,23627,30.19900,67.00970,-2772048,20161101011500,https://www.thenews.com.pk/print/161437-Quetta...
17,594563069,20161002,201610,2016,2016.7452,MIL,ARMY,NaN,NaN,NaN,...,5,"Balochistan, Balochistan, Pakistan",PK,PK02,40300,28.47850,65.64360,-2755738,20161101011500,https://www.thenews.com.pk/print/161437-Quetta...
18,594563070,20161002,201610,2016,2016.7452,USA,UNITED STATES,USA,NaN,NaN,...,2,"Oklahoma, United States",US,USOK,NaN,35.53760,-96.92470,OK,20161101011500,http://leglobaliste.com/2016/11/01/russian-fed...
19,594563071,20161002,201610,2016,2016.7452,USA,UNITED STATES,USA,NaN,NaN,...,2,"Oklahoma, United States",US,USOK,NaN,35.53760,-96.92470,OK,20161101011500,http://leglobaliste.com/2016/11/01/russian-fed...
20,594563072,20161025,201610,2016,2016.8082,NaN,NaN,NaN,NaN,NaN,...,4,"Kukerin, Western Australia, Australia",AS,AS08,5475,-33.18330,118.08300,-1582402,20161101011500,http://www.stockjournal.com.au/story/4260141/e...
21,594563073,20161025,201610,2016,2016.8082,NaN,NaN,NaN,NaN,NaN,...,4,"Browns Well, Western Australia, Australia",AS,AS08,5553,-24.51670,115.76700,-1562076,20161101011500,http://www.stockjournal.com.au/story/4252786/l...
22,594563074,20161025,201610,2016,2016.8082,NaN,NaN,NaN,NaN,NaN,...,4,"Maungdaw, Rakhine State, Myanmar",BM,BM01,41812,20.81670,92.36670,-429034,20161101011500,http://www.myanmarnews.net/index.php/sid/24901...
23,594563075,20161025,201610,2016,2016.8082,AUS,AUSTRALIA,AUS,NaN,NaN,...,4,"Browns Well, Western Australia, Australia",AS,AS08,5553,-24.51670,115.76700,-1562076,20161101011500,http://www.stockjournal.com.au/story/4252786/l...
24,594563076,20161025,201610,2016,2016.8082,AUT,VIENNA,AUT,NaN,NaN,...,4,"Vienna, Wien, Austria",AU,AU09,5672,48.20000,16.36670,-1995499,20161101011500,http://www.businesstimes.com.sg:80/energy-comm...
25,594563077,20161025,201610,2016,2016.8082,BUSLEG,INDUSTRY,NaN,NaN,NaN,...,4,"Taplan, South Australia, Australia",AS,AS05,5284,-34.55000,140.88300,-1603582,20161101011500,http://www.stockjournal.com.au/story/4252786/l...
26,594563078,20161025,201610,2016,2016.8082,BUSLEG,INDUSTRY,NaN,NaN,NaN,...,4,"Taplan, South Australia, Australia",AS,AS05,5284,-34.55000,140.88300,-1603582,20161101011500,http://www.stockjournal.com.au/story/4252786/l...
27,594563079,20161025,201610,2016,2016.8082,CVL,SETTLEMENT,NaN,NaN,NaN,...,1,Israel,IS,IS,NaN,31.50000,34.75000,IS,20161101011500,http://www.palestinemonitor.org/details.php?id...
28,594563080,20161025,201610,2016,2016.8082,EDU,STUDENT,NaN,NaN,NaN,...,5,"Bay Of Plenty, Bay of Plenty, New Zealand",NZ,NZE8,22380,-38.33330,176.75000,11483126,20161101011500,http://www.scoop.co.nz/stories/ED1611/S00002/s...
29,594563081,20161025,201610,2016,2016.8082,IDN,JAKARTA,IDN,NaN,NaN,...,1,India,IN,IN,NaN,20.00000,77.00000,IN,20161101011500,http://www.freemalaysiatoday.com/category/worl...
30,594563082,20161025,201610,2016,2016.8082,MNCUSA,DISNEY,USA,NaN,NaN,...,1,United States,US,US,NaN,38.00000,-97.00000,US,20161101011500,https://www.yahoo.com/news/doctor-strange-fant...
31,594563083,20161025,201610,2016,2016.8082,NZL,BAY OF PLENTY,NZL,NaN,NaN,...,4,"Waitomo, New Zealand (general), New Zealand",NZ,NZ00,22389,-38.26670,175.10000,-1521103,20161101011500,http://www.scoop.co.nz/stories/ED1611/S00002/s...
32,594563084,20161025,201610,2016,2016.8082,SYR,SYRIA,SYR,NaN,NaN,...,4,"Raqqah, Ar Raqqah, Syria",SY,SY04,26371,35.95000,39.01670,-2538949,20161101011500,https://www.middleeastmonitor.com/20161031-pen...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226335,594878548,20161101,201611,2016,2016.8247,VEN,VENEZUELA,VEN,NaN,NaN,...,1,Mexico,MX,MX,NaN,23.00000,-102.00000,MX,20161101234500,http://oilprice.com/Energy/Energy-General/Whic...
226336,594878549,20161101,201611,2016,2016.8247,VEN,VENEZUELA,VEN,NaN,NaN,...,4,"Caracas, Distrito Federal, Venezuela",VE,VE25,31959,10.50000,-66.91670,-938457,20161101234500,http://latino.foxnews.com/latino/politics/2016...
226337,594878550,20161101,201611,2016,2016.8247,VEN,VENEZUELA,VEN,NaN,NaN,...,1,Colombia,CO,CO,NaN,4.00000,-72.00000,CO,20161101234500,http://latino.foxnews.com/latino/politics/2016...
226338,594878551,20161101,201611,2016,2016.8247,VEN,VENEZUELA,VEN,NaN,NaN,...,4,"Chacao, Anzoágui, Venezuela",VE,VE02,32060,8.97692,-63.69420,-3853428,20161101234500,http://www.thestate.com/news/nation-world/worl...
226339,594878552,20161101,201611,2016,2016.8247,VENGOV,VENEZUELA,VEN,NaN,NaN,...,1,United States,US,US,NaN,38.00000,-97.00000,US,20161101234500,http://www.thestate.com/news/nation-world/worl...
226340,594878553,20161101,201611,2016,2016.8247,VENMIL,VENEZUELA,VEN,NaN,NaN,...,4,"Caracas, Distrito Federal, Venezuela",VE,VE25,31959,10.50000,-66.91670,-938457,20161101234500,http://latino.foxnews.com/latino/politics/2016...
226341,594878554,20161101,201611,2016,2016.8247,VNM,HANOI,VNM,NaN,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,25106,55.75220,37.61560,-2960561,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226343,594878556,20161101,201611,2016,2016.8247,VNM,VIETNAM,VNM,NaN,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,25106,55.75220,37.61560,-2960561,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226344,594878557,20161101,201611,2016,2016.8247,VNM,HANOI,VNM,NaN,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,25106,55.75220,37.61560,-2960561,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226345,594878558,20161101,201611,2016,2016.8247,VNM,HANOI,VNM,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226346,594878559,20161101,201611,2016,2016.8247,VNM,HANOI,VNM,NaN,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,25106,55.75220,37.61560,-2960561,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226347,594878560,20161101,201611,2016,2016.8247,VNM,VIETNAM,VNM,NaN,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,25106,55.75220,37.61560,-2960561,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226348,594878561,20161101,201611,2016,2016.8247,VNM,HANOI,VNM,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226349,594878562,20161101,201611,2016,2016.8247,VNM,VIETNAM,VNM,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226351,594878564,20161101,201611,2016,2016.8247,VNM,VIETNAM,VNM,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.89510,-77.03640,531871,20161101234500,http://www.eastasiaforum.org/2016/11/02/will-a...
226356,594878569,20161101,201611,2016,2016.8247,YEM,YEMENI,YEM,NaN,NaN,...,4,"Riyadh, Ar Riya?, Saudi Arabia",SA,SA10,25316,24.64080,46.77280,-3093009,20161101234500,http://aa.com.tr/en/middle-east/yemeni-vice-pr...
226357,594878570,20161101,201611,2016,2016.8247,YEM,YEMENI,YEM,NaN,NaN,...,4,"Riyadh, Ar Riya?, Saudi Arabia",SA,SA10,25316,24.64080,46.77280,-3093009,20161101234500,http://aa.com.tr/en/middle-east/yemeni-vice-pr...
226362,594878575,20161101,201611,2016,2016.8247,apa,APACHE,NaN,NaN,apa,...,2,"Louisiana, United States",US,USLA,NaN,31.18010,-91.87490,LA,20161101234500,http://www.upstreamonline.com/live/1186546/apa...
226363,594878576,20161101,201611,2016,2016.8247,dak,SIOUX,NaN,NaN,dak,...,3,"Middletown, Connecticut, United States",US,USCT,CT007,41.56230,-72.65070,208877,20161101234500,http://www.middletownpress.com/article/MI/2016...
226364,594878577,20161101,201611,2016,2016.8247,idg,INDIGENOUS,NaN,NaN,idg,...,4,"Leslieville, Alberta, Canada",CA,CA01,154724,52.38330,-114.60000,-567893,20161101234500,https://nowtoronto.com/news/support-first-nati...
226365,594878578,20161101,201611,2016,2016.8247,idg,INDIGENOUS,NaN,NaN,idg,...,4,"Leslieville, Alberta, Canada",CA,CA01,154724,52.38330,-114.60000,-567893,20161101234500,https://nowtoronto.com/news/support-first-nati...
226366,594878579,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,4,"Kashmiri, Punjab, Pakistan",PK,PK04,23677,32.03870,73.75100,6104745,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226367,594878580,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,1,India,IN,IN,NaN,20.00000,77.00000,IN,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226368,594878581,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,5,"Kashmir, Jammu and Kashmir, India",IN,IN12,72809,33.91670,76.66670,-2098229,20161101234500,http://timesofindia.indiatimes.com/india/Griev...
226369,594878582,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,4,"Kashmiri, Punjab, Pakistan",PK,PK04,23677,32.03870,73.75100,6104745,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226370,594878583,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,1,India,IN,IN,NaN,20.00000,77.00000,IN,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226371,594878584,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,4,"Kashmiri, Punjab, Pakistan",PK,PK04,23677,32.03870,73.75100,6104745,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226372,594878585,20161101,201611,2016,2016.8247,kas,KASHMIRI,NaN,NaN,kas,...,1,India,IN,IN,NaN,20.00000,77.00000,IN,20161101234500,http://www.indiawest.com/blogs/why-hindu-ameri...
226373,594878586,20161101,201611,2016,2016.8247,ran,RANA,NaN,NaN,ran,...,4,"Mumbai, Maharashtra, India",IN,IN16,70184,18.97500,72.82580,-2092174,20161101234500,http://www.indiawest.com/entertainment/bollywo...
226374,594878587,20161101,201611,2016,2016.8247,ran,RANA,NaN,NaN,ran,...,1,Pakistan,PK,PK,NaN,30.00000,70.00000,PK,20161101234500,http://www.indiawest.com/entertainment/bollywo...

In [18]:
iso3166.countries_by_name

AttributeError: 'dict' object has no attribute 'head'

In [25]:
countries = iso3166.countries_by_name

In [30]:
countries['UNITED STATES OF AMERICA'].alpha2

'US'

In [23]:

[countries[key].alpha2 in results["ActionGeo_CountryCode"] for key in countries.keys()]

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [8]:
gapminder = px.data.gapminder().query("year == 2007")
gapminder

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
71,Australia,Oceania,2007,81.235,20434176,34435.367440,AUS,36
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
95,Bahrain,Asia,2007,75.635,708573,29796.048340,BHR,48
107,Bangladesh,Asia,2007,64.062,150448339,1391.253792,BGD,50
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
131,Benin,Africa,2007,56.728,8078314,1441.284873,BEN,204
143,Bolivia,Americas,2007,65.554,9119152,3822.137084,BOL,68
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
167,Botswana,Africa,2007,50.728,1639131,12569.851770,BWA,72
179,Brazil,Americas,2007,72.390,190010647,9065.800825,BRA,76
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100
203,Burkina Faso,Africa,2007,52.295,14326203,1217.032994,BFA,854
215,Burundi,Africa,2007,49.580,8390505,430.070692,BDI,108
227,Cambodia,Asia,2007,59.723,14131858,1713.778686,KHM,116
239,Cameroon,Africa,2007,50.430,17696293,2042.095240,CMR,120
251,Canada,Americas,2007,80.653,33390141,36319.235010,CAN,124
263,Central African Republic,Africa,2007,44.741,4369038,706.016537,CAF,140
275,Chad,Africa,2007,50.651,10238807,1704.063724,TCD,148
287,Chile,Americas,2007,78.553,16284741,13171.638850,CHL,152
299,China,Asia,2007,72.961,1318683096,4959.114854,CHN,156
311,Colombia,Americas,2007,72.889,44227550,7006.580419,COL,170
323,Comoros,Africa,2007,65.152,710960,986.147879,COM,174
335,"Congo, Dem. Rep.",Africa,2007,46.462,64606759,277.551859,COD,180
347,"Congo, Rep.",Africa,2007,55.322,3800610,3632.557798,COG,178
359,Costa Rica,Americas,2007,78.782,4133884,9645.061420,CRI,188
...,...,...,...,...,...,...,...,...
1355,Sierra Leone,Africa,2007,42.568,6144562,862.540756,SLE,694
1367,Singapore,Asia,2007,79.972,4553009,47143.179640,SGP,702
1379,Slovak Republic,Europe,2007,74.663,5447502,18678.314350,SVK,703
1391,Slovenia,Europe,2007,77.926,2009245,25768.257590,SVN,705
1403,Somalia,Africa,2007,48.159,9118773,926.141068,SOM,706
1415,South Africa,Africa,2007,49.339,43997828,9269.657808,ZAF,710
1427,Spain,Europe,2007,80.941,40448191,28821.063700,ESP,724
1439,Sri Lanka,Asia,2007,72.396,20378239,3970.095407,LKA,144
1451,Sudan,Africa,2007,58.556,42292929,2602.394995,SDN,736
1463,Swaziland,Africa,2007,39.613,1133066,4513.480643,SWZ,748
1475,Sweden,Europe,2007,80.884,9031088,33859.748350,SWE,752
1487,Switzerland,Europe,2007,81.701,7554661,37506.419070,CHE,756
1499,Syria,Asia,2007,74.143,19314747,4184.548089,SYR,760
1511,Taiwan,Asia,2007,78.400,23174294,28718.276840,TWN,158
1523,Tanzania,Africa,2007,52.517,38139640,1107.482182,TZA,834
1535,Thailand,Asia,2007,70.616,65068149,7458.396327,THA,764
1547,Togo,Africa,2007,58.420,5701579,882.969944,TGO,768
1559,Trinidad and Tobago,Americas,2007,69.819,1056608,18008.509240,TTO,780
1571,Tunisia,Africa,2007,73.923,10276158,7092.923025,TUN,788
1583,Turkey,Europe,2007,71.777,71158647,8458.276384,TUR,792
1595,Uganda,Africa,2007,51.542,29170398,1056.380121,UGA,800
1607,United Kingdom,Europe,2007,79.425,60776238,33203.261280,GBR,826
1619,United States,Americas,2007,78.242,301139947,42951.653090,USA,840
1631,Uruguay,Americas,2007,76.384,3447496,10611.462990,URY,858
1643,Venezuela,Americas,2007,73.747,26084662,11415.805690,VEN,862
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:

gapminder = px.data.gapminder().query("year == 2007")
fig = px.line_geo(gapminder, locations="iso_alpha", 
                  color="continent", # "continent" is one of the columns of gapminder 
                  projection="orthographic")
fig.show()